### ISSUE TITLE
Request for BSS-4FSK ID

### ISSUE THREAD

**Issue by zanco** [projecthorus/horusdemodlib#10]
Please assing an ID to BSS-4FSK ( SA6BSS )

**Comment by darksidelemm** [comment]
ID #34 assigned.

**Comment by sp3cet** [comment]
Hello !
Please add SP3CET-4FSK.
73! Thanks

**Comment by sp3cet** [comment]
Please add to my Call 4FSK id v1 - Plese 
SP3CET-4FSK
Thanks ! Wladek

**Comment by zanco** [comment]
> Please add to my Call 4FSK id v1 - Please SP3CET-4FSK Thanks ! Wladek

SP3CET please start a new issue, now I get the messages in my mailbox, usual all radio amateurs file their own request, not add on to an existing issue which was closed after I got the ID I requested
