### ISSUE TITLE
Payload ID request: ON4BCY

### ISSUE THREAD

**Issue by Bastiti** [projecthorus/horusdemodlib#103]
Hello,

Is it possible for you to add my callsign: ON4BCY to the payload id ?

I'm using HORUS V2, with RS41NG.

Thanks in advance. 

73 ON4BCY

**Comment by Bastiti** [comment]
Oh, and is it possible to add ON2KGC, for my father ? 

Am getting a sonde for him too

**Comment by darksidelemm** [comment]
The following IDs assigned:
```
327, ON4BCY
328, ON2KGC
```

**Comment by Bastiti** [comment]
awesome, thanks !
