### ISSUE TITLE
Hi from YT3GTI

### ISSUE THREAD

**Issue by YT3GTI** [projecthorus/horusdemodlib#107]
I like to request a payload ID fot YT3GTI-4FSK.

TNX

**Comment by darksidelemm** [comment]
Hi, I'm no longer allocating Horus Binary V1 callsigns. 

Please switch to using firmware that supports Horus Binary v2, e.g. https://github.com/mikaelnousiainen/RS41ng
and i'll happily allocate a V2 callsign.

**Comment by YT3GTI** [comment]
Ok , will be soon . 
Tnx

**Comment by YT3GTI** [comment]
Can you please make payload ID  YT3GTI-V2 then ?

**Comment by darksidelemm** [comment]
Done, assigned ID 337.

**Comment by YT3GTI** [comment]
Tnx @darksidelemm  Mark
