### ISSUE TITLE
 Request a V2 payload ID

### ISSUE THREAD

**Issue by F5MVO** [projecthorus/horusdemodlib#113]
Request a V2 payload ID

Hi,

Please assign a payload ID for:

F5MVO

Thanks,

André

**Comment by F5RZC** [comment]
Hi Mark,

Please, can you assign me a payload ID for:

F5RZC

Many thanks,
Jeff.

**Comment by darksidelemm** [comment]
The following IDs have been assigned: 
342, F5MVO
343, F5RZC

**Comment by F5RZC** [comment]
Could you change Mark, F5RZC to F5RZC-4FSK if you have to do this to appear with this callsign on the server.
Thanks in advance,
Sincerely, Jeff

**Comment by darksidelemm** [comment]
There's no need for the -4FSK suffix on amateur.sondehub.org

**Comment by F5RZC** [comment]
Many thanks for the feedback Mark.73s

**Comment by F5RZC** [comment]
Hello Mark,
Can you pse give me a ID for my friend  F6ASP
Many thanks for feedback. 
73s.
Jeff, F5RZC

**Comment by darksidelemm** [comment]
Done, assigned ID 344
