### ISSUE TITLE
payload ID request

### ISSUE THREAD

**Issue by ON2ON-HAM** [projecthorus/horusdemodlib#116]
Hi,

I believe this is where I request for a "Payload ID"
for : 

ON2ON-4FSK-V2

32-byte payload

Thanks in advance,

Luke

**Comment by darksidelemm** [comment]
Hi Luke,

If you don't mind, I'll drop the -4FSK- bit? It's fairly obvious on amateur.sondehub.org what the modulation is now.

I've assigned ID 355
