### ISSUE TITLE
tonespacing

### ISSUE THREAD

**Issue by edegraaff** [projecthorus/horusdemodlib#118]
Hi, i am searchin where i could set the tonespacing... would like to set it  like the horusgui can, dit i overlooked something in the code?  would like to set tonespacing to 248

**Comment by darksidelemm** [comment]
By default the command-line horus demod will look for tones at any spacing in the passband (e.g. the same as in Horus-GUI if the 'Mast Estimator' is turned off).

There is a *small* decode performance hit at very weak SNRs with the mask estimator disabled. 

If you want to specify a tone spacing to horus_demod, you can do so with the -s option, e.g.:

```
rtl_fm -M raw -F9 -s 48000 -p $PPM $GAIN_SETTING$BIAS_SETTING -f $SDR_RX_FREQ | $DECODER -q --stats=5 -g -m binary -s 248 --fsk_lower=$FSK_LOWER --fsk_upper=$FSK_UPPER - - | python -m horusdemodlib.uploader --freq_hz $SDR_RX_FREQ --freq_target_hz $RXFREQ $@
```
(Note the addition of `-s 248` after the `-m binary` option.)

What transmitter are you using that uses a 248 Hz tone spacing? Be aware that if you set this, you will not be able to decode anything with tone spacings other than this, e.g. reflashed RS41s.

**Comment by edegraaff** [comment]
> By default the command-line horus demod will look for tones at any spacing in the passband (e.g. the same as in Horus-GUI if the 'Mast Estimator' is turned off).
> 
> There is a _small_ decode performance hit at very weak SNRs with the mask estimator disabled.
> 
> If you want to specify a tone spacing to horus_demod, you can do so with the -s option, e.g.:
> 
> ```
> rtl_fm -M raw -F9 -s 48000 -p $PPM $GAIN_SETTING$BIAS_SETTING -f $SDR_RX_FREQ | $DECODER -q --stats=5 -g -m binary -s 248 --fsk_lower=$FSK_LOWER --fsk_upper=$FSK_UPPER - - | python -m horusdemodlib.uploader --freq_hz $SDR_RX_FREQ --freq_target_hz $RXFREQ $@
> ```
> 
> (Note the addition of `-s 248` after the `-m binary` option.)
> 
> What transmitter are you using that uses a 248 Hz tone spacing? Be aware that if you set this, you will not be able to decode anything with tone spacings other than this, e.g. reflashed RS41s.

Hi,  Ben is testing with a HAB PE2BZ-4FSK with a reflashed RS41 and we try to get a signal from him to my horusdemolib, and leave that one running unattended for several days to see if we get a ping/pong this one is working at the 23cm band and Ben suggested to use as test another tonespacing. 

Regards
Eelco nl13974

**Comment by darksidelemm** [comment]
OK? Given it's a RS41 it should be the default 270 Hz tone spacing. I'm not sure how you're getting a RS41 to transmit on 23cm however.
