### ISSUE TITLE
 Reques

### ISSUE THREAD

**Issue by YU1WAT** [projecthorus/horusdemodlib#119]
Hi, can I request for a planned future fligt the V2 ID
YU1WAT-4FSK
YU1WAT-APRS

**Comment by darksidelemm** [comment]
Hi, we can probably just make this YU1WAT for the V2 callsign, if that's OK?

**Comment by darksidelemm** [comment]
Ahh, I see you already have a V2 ID assigned to the callsign YU1WAT (ID 338).

Is this all that is required?

**Comment by YU1WAT** [comment]
Then add -4FSK

**Comment by darksidelemm** [comment]
I'm not quite sure I understand.
You are launching 2 balloons? Why not something like YU1WAT and YU1WAT-2 then?

**Comment by YU1WAT** [comment]
Okay, this variant is also possible.

**Comment by darksidelemm** [comment]
OK, I have allocated payload ID 358 to the callsign YU1WAT-2

**Comment by YU1WAT** [comment]
Thank you.
