### ISSUE TITLE
Debugging and get it running.

### ISSUE THREAD

**Issue by edegraaff** [projecthorus/horusdemodlib#121]
Hi Mark, 

I am trying to get the horusdemolib working in a way i can see data comming in. But somewhere i fail and have no clue where. 
I build the HorysBinary_tracker developed by Roel, and from there i was able to get data from the tracker into the sdr and from there decoded it in the horus-gui. In the Horus-gui i needed to change two options: baudrate to 50 and spacing to 244 to get the gui version working but now i want to get also the horusdemolib working. Where do i make an mistake?

![image](https://user-images.githubusercontent.com/12442749/212492686-999beb72-7672-437e-83dd-39f1efa74be1.png)

Now i want to be able to decode the same telegram at the horusdemolib device but until now i fail here. 
I tune at 434569766 hrz 
RXFREQ=434569766
RXBANDWIDTH=15000
STATS_OUTPUT=1
![image](https://user-images.githubusercontent.com/12442749/212492879-7404c5e4-0e36-43e2-8056-11a36376dc35.png)
it starts up but i am not able to get the telegram 
how could i see the data is seen somehow? there is no waterfall but also no other options to check or is there some sort of logging?

**Comment by darksidelemm** [comment]
Probably because the command-line utility won't have the baud rate set. You will have to add a `--rate=50` option to the horus_demod call.

Don't worry about the frequency shift, that will get detected automatically.

May I ask why you are running 50 baud? If you run the standard 100 baud then you'll be picked up by all the existing receivers out there, and it will cause a lot less confusion...

**Comment by edegraaff** [comment]
> Probably because the command-line utility won't have the baud rate set. You will have to add a `--rate=50` option to the horus_demod call.
> 
> Don't worry about the frequency shift, that will get detected automatically.
> 
> May I ask why you are running 50 baud? If you run the standard 100 baud then you'll be picked up by all the existing receivers out there, and it will cause a lot less confusion...

Hi Mark, it is more because i had that part up and working tody, and i did not want to change things that worked to do the next step. I will ask Roel if i am able to change the rate to 100 baud i agree it is more common, and maybe i will also check if i am able to set de freq shift ro 270.

**Comment by edegraaff** [comment]
Hi Mark, 
I made some modifications in the settings file of the HorusBinaryTracker created by Roel. I am now able to get the telegrams also decoded in horusdemolib :-) 
2023-01-23 22:11:27,996 WARNING: Sondehub Amateur Uploader - Payload ID 4FSKTEST is for testing purposes only, and should not be used on an actual flight. Refer here: https://github.com/projecthorus/horusdemodlib/wiki#how-do-i-transmit-it
2023-01-23 22:11:27,997 INFO: Decoded Binary Packet (SNR 13.6 dB): $$4FSKTEST,23,21:11:23,52.12488,4.44922,62,0,8,13,3.22*FB89
2023-01-23 22:11:29,972 INFO: Sondehub Amateur Uploader - Uploaded 1 telemetry packets to Sondehub Amateur in 0.5 seconds.

Chain is now complete, the telegrams are send by arduino pro-mini with 3.3v 8 mhz and with HTB and decoded with horus-gui as well as the horusdemolib with 100 baud and tonespacing 270 hrz. 

I hope this info is usable for others to. 

regards
eelco nl13974

**Comment by darksidelemm** [comment]
I hope that Roel's code will be updated to support Horus Binary v2 telemetry!

I'm no longer allocating any more V1 IDs...

**Comment by edegraaff** [comment]
> I hope that Roel's code will be updated to support Horus Binary v2 telemetry!
> 
> I'm no longer allocating any more V1 IDs...

As far as i know he is already, this evening we did some additional testing and all seem ok, we dropped the transmitter in the fridge at -20 and it stays stable.  We will play with the baudrate a bit more the upomming days.  Keep you updated, for now we have it working.

**Comment by edegraaff** [comment]
Last info, i was able to get the 100 baud working, the reception to the horusdemolib worked without any changes. I also tested the horus v2 and this also worked! Thanks to Roel and Mark to have this nice projects. More info can be found on my blog. https://www.fishfreak.org/iot-raspberry-pi-en-home-assistant/lora/ i wrote down all  results over the last 2 years.
