### ISSUE TITLE
start_rtlsdr.sh no device selector 

### ISSUE THREAD

**Issue by zanco** [projecthorus/horusdemodlib#124]
Hi, when starting the start_rtlsdr.sh it chooses the first available rtl device.

Would be nice to have the device=0 option as default in the user.cfg which can be changed by user to device / serial number.

Thanks,

Ben

**Comment by duk3luk3** [comment]
I added `-d $1` to the rtl_ command in the script so I can select the device.

Haven't gotten around to PR it yet.

**Comment by darksidelemm** [comment]
Fixed in https://github.com/projecthorus/horusdemodlib/releases/tag/v0.3.12
