### ISSUE TITLE
Payload ID for "M7ONS"

### ISSUE THREAD

**Issue by star210** [projecthorus/horusdemodlib#128]
Hi

Please allocate a HORUS v2 ID for "M7ONS" (Oscar not 0)

Star

**Comment by darksidelemm** [comment]
I have allocated Horus V2 payload ID 371 to that callsign.

I note that you are testing on the map with a LoRa payload, also with callsign M7ONS.
You must use different callsigns for each modulation you are transmitting, else it will cause some odd issues on the map, and will mess up data export.
