### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by robertcb1** [projecthorus/horusdemodlib#13]
Hello.

Please set the payload ID 

line 47 
position 37  

SQ5RB-4FSK

Thank you

Robert SQ5RB

**Comment by darksidelemm** [comment]
Done, assigned Payload ID #37 to SQ5RB-4FSK

**Comment by robertcb1** [comment]
Hello.

Please set the payload ID

line 61
position 51

SQ3PMN-4FSK

Thank you

Robert SQ5RB
