### ISSUE TITLE
Payload ID needed

### ISSUE THREAD

**Issue by dn3rw** [projecthorus/horusdemodlib#133]
Hello,
can I also get an ID for Horus V2 for DM7RM? If I want to use an other mode like RTTY for e.g., do I need an additional ID or can I use the same for that?

Thanks in advance.

73's, Ralf DM7RM

**Comment by darksidelemm** [comment]
I've allocated ID 382 to that callsign.

A payload ID is only applicable to the Horus binary mode, and just serves as a mapping between the payload ID you configure on your tracker, and a callsign that shows up on the Sondehub-amateur map.

If you are transmitting with a different mode, I would suggest making the callsign different to what you use with Horus Binary, to avoid oddness on the maps.
