### ISSUE TITLE
Installation Looked Good, Then ...

### ISSUE THREAD

**Issue by lukepurdy64** [projecthorus/horusdemodlib#137]
I've tried two different SDRs and the installation on my Raspberry Pi appeared to be fine.  However, when I try to run the start script, I get this.  It appears to see the hardware, but can't talk to it.  Any ideas on next steps?

> $ sudo /home/pi/horusdemodlib/start_rtlsdr.sh &
> [1] 1217
> Found horus_demod.
> Found bc.
> Entering venv.
> Using SDR Centre Frequency: 434194000 Hz.
> Using FSK estimation range: 1000 - 11000 Hz
> Using AGC.
> Found 1 device(s):
>   0:  Realtek, RTL2838UHIDIR, SN: 00000001
> 
> Using device 0: Generic RTL2832U OEM
> usb_claim_interface error -6
> Failed to open rtlsdr device #0.
> 
> [1]+  Exit 1

**Comment by dbrooke** [comment]
You probably already have something running which is accessing the SDR, possibly from previously running the same command as the trailing '&' will put it in background and this is likely not what you want when starting it from the command line.

Also sudo shouldn't be needed as the program can run as an unprivileged user as long as the rtl-sdr software was installed with the  correct udev rules.

**Comment by lukepurdy64** [comment]
That was it! Thanks so much.
