### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by dn3rw** [projecthorus/horusdemodlib#139]
Hello Mark,
sorry, want to ask you, can I get an addional ID for further projects. I could need one for 
BCH-4FSK
if possible.

Thanks and greetings from South Germany.
Ralf

**Comment by darksidelemm** [comment]
For the Horus v2 ID's, we've every gone with the convention of having a -V2 suffix, not including a suffix at all, since amateur.sondehub.org shows the modulation details anyway.

Can you confirm what callsign you want based on this?

**Comment by dn3rw** [comment]
Ah, ok. Then please for DM7RM-2 would be helpful.

**Comment by darksidelemm** [comment]
Done, ID 393 :-)
