### ISSUE TITLE
rtty checksum problem ?

### ISSUE THREAD

**Issue by zanco** [projecthorus/horusdemodlib#14]
![image](https://user-images.githubusercontent.com/4477734/104642035-c7b6b100-56aa-11eb-9a8d-2a872a38e3d7.png)

appears to be a good checksum.

![image](https://user-images.githubusercontent.com/4477734/104642128-e7e67000-56aa-11eb-888c-344a16aa0009.png)

Gives: 2021-01-14 20:55:32,621 ERROR: Decode Failed: Could not parse RTTY Sentence - CRC Fail.

Can this be fixed ?

**Comment by darksidelemm** [comment]
Yep, I think I know where that bug came from... will fix.

**Comment by darksidelemm** [comment]
Hmm maybe not. The above screenshots suggest that the checksum of the sentence was 0x001A, and that it wasn't being added to the string with the appropriate zero padding.

I just ran a few tests on the latest commit where I overrode the checksum with values like 0x1234, 0x0234, and 0x0034 to check the zero padding was working... and it seems to be OK?

Maybe check you are on the latest commit, and if you still see issues, we can work through them on IRC.

**Comment by darksidelemm** [comment]
Issue was the tracker was using a XOR checksum. horusdemodlib will not support XOR checksums, they are too susceptible to false-positives, which results in bad data being pushed into habitat.
