### ISSUE TITLE
Add generator for phi0.c

### ISSUE THREAD

**Issue by SoftwareToolworks** [projecthorus/horusdemodlib#140]
The file phi0.c was generated by a python file.

Just to be complete, you may want to add the file to /src. It is located at:

https://github.com/drowe67/codec2/blob/master/script/gen_phi0

and maybe rename it to gen_phi0.py

**Comment by darksidelemm** [comment]
Since this file doesn't change, I've just added a link to the script in the codec2 repository at the top of phi0.c
