### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by PD2HSB** [projecthorus/horusdemodlib#143]
Hello,

Could you provide me the information to receive a payload ID for my first flight?

73

Hans 
PD2HSB

**Comment by darksidelemm** [comment]
Hi,

What callsign would you like used? Just PD2HSB?

73
Mark VK5QI

**Comment by PD2HSB** [comment]
Hi Mark,

Sorry all this ballooning is very new for me...
Do I need the -4FSK extension in the name?
I want to fly with the Horus2 mode.

A lot of questions from a newbee, again sorry for that.

73
Hans
PD2HSB

Op vr 24 mrt 2023 om 09:27 schreef Mark Jessop ***@***.***>:
