### ISSUE TITLE
Payload ID request

### ISSUE THREAD

**Issue by YU1WAT** [projecthorus/horusdemodlib#154]
Hello Mark,
Sorry, want to ask you, can I get an addional ID for further Horus V1 projects. 
I could need one for IKAR-4FSK if possible.

Explanation
I am using RS41HUP for a future project.
It is very important to me because of the "deep sleep" mode.
I'm hoping for a positive answer.
I will be forced to stop the project due to lack of ID.

**_Thanks and greetings from Serbia._**
Vinko, YU1WAT

**Comment by darksidelemm** [comment]
Sorry no, I will not be supporting any further Horus v1 IDs.
Note that the deep sleep approach was never reliable, and I found all sorts of odd GPS locking issues

I would suggest talking to the RS41ng developer about implementing Power-Save modes.
