### ISSUE TITLE
Payload ID request

### ISSUE THREAD

**Issue by sq5nwi** [projecthorus/horusdemodlib#16]
Hi, please assign the new payload ID for our club callsign: SP5YAM
Thank you for the Horus project. :)
-- 
73 de Krzysiek (Chris) SQ5NWI

**Comment by darksidelemm** [comment]
Hi Chris,

Do you want just the callsign SP5YAM, or with -4FSK on the end to tell it apart from other modes you might use?

73
Mark

**Comment by sq5nwi** [comment]
Hi Mark,

I was thinking about this for a while and not sure in fact. ;)
+ one object on the Habitat map
- little bit more difficult to differ between RTTY data and 4FSK data in log for analysis
What is your advise from experience?
Is it possible to edit it later if I would change my mind?
--
73 de SQ5NWI

**Comment by darksidelemm** [comment]
I would suggest using SP5YAM-4FSK. Telemetry from two different sources will not merge well on the map, and you would need to be sure they are exactly the same format. The -4FSK suffix also makes it obvious that listeners need to use the Horus Binary demodulator.

I've allocated Payload ID 40 to SP5YAM-4FSK

Let me know if you want it changed, it's not difficult to do.

73
Mark VK5QI

**Comment by sq5nwi** [comment]
Great and super quick support! Thank you Mark.
Let's play with this.
We'll test it in the flight next Sunday.
-- 
73 de SQ5NWI
