### ISSUE TITLE
payload ID request

### ISSUE THREAD

**Issue by BoXJakub** [projecthorus/horusdemodlib#161]
Hi, I would like to get an ID for my payload: SP3ZHP-4FSK.

**Comment by darksidelemm** [comment]
Hi,

I've assigned Horus V2 ID 429 to call SP3ZHP.

Note that I haven't added the -4FSK suffix. The Sondehub-Amateur tracker now shows modulation information in the payload details area, so the suffix to indicate the modulation type is no longer necessary.

73
Mark
