### ISSUE TITLE
Additional Callsigns for DL1MRZ

### ISSUE THREAD

**Issue by MoritzFeiler** [projecthorus/horusdemodlib#175]
Hey there, 
i was wondering if it is possible to get multiple IDs registered for one callsign and if there is a limit to the ID name length.
Because we have multiple Sondes and often fly two of them at the same time for redundancy, I think it would be nice to have different IDs to differentiate them. Ideally something like: 
DL1MRZ-Bubble_1
DL1MRZ-Bubble_2
DL1MRZ-Bubble_3
DL1MRZ-Bubble_4

If that's too long, just the callsign and the numbers 1-4 would be allright as well (i.e. DL1MRZ-1). 
Thank you very much!

73 
Moritz

**Comment by darksidelemm** [comment]
Those are probably getting a bit long for display on the tracker. 

I've done the following:
```
444, DL1MRZ-1
445, DL1MRZ-2
446, DL1MRZ-3
447, DL1MRZ-4
```

Let me know if this is OK!

**Comment by MoritzFeiler** [comment]
Awesome, thank you very much!
