### ISSUE TITLE
start_rtlsdr.sh: ModuleNotFoundError: No module named 'crcmod'

### ISSUE THREAD

**Issue by j0uni** [projecthorus/horusdemodlib#176]
I'm running start_rtlsdr.sh on Ubuntu machine and it ends up in error No module named 'crcmod'.

I have installed requirements.txt on pip3 (I needed to mod the script to use python3 too). 

If I run "python3 -m horusdemodlib.uploader" alone, it starts and works. Of course it is not receiving any data so I don't know if that has effect.

Also the rtl_fm + decoded part works alone fine.

Somehow the piping to python just "looses" all modules that have been installed to the system + in virtual environment (no difference).

**Comment by j0uni** [comment]
Also if I run  

echo "hello" | python3 -m horusdemodlib.uploader

that works too without nagging about missing crcmod.

**Comment by darksidelemm** [comment]
This sounds like the python version where the packages have been installed
is not the same as what is running when you run the commands.

**Comment by j0uni** [comment]
Thanks for the tip. I replaced the python-command from the script with

/home/jouni/horusdemodlib//venv/bin/python3

And now it works.

**Comment by darksidelemm** [comment]
The startup scripts should enter the venv automatically if it exists... I'm
wondering why thats not working...

**Comment by j0uni** [comment]
:D Because I commented it out when I was trying to debug this.

Brought those rows back and now it works. I don't know why it didn't work in the first place. Strange.
