### ISSUE TITLE
Problems starting start-rtlsdr

### ISSUE THREAD

**Issue by heijsteeg** [projecthorus/horusdemodlib#179]
I get the following error after starting the program. Help appreciated where to look. 

Found horus_demod.
Found bc.
Entering venv.
Using SDR Centre Frequency: 434194000 Hz.
Using FSK estimation range: 1000 - 11000 Hz
Using AGC.
Setting estimator limits to 1000 to 11000 Hz.
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/horusdemodlib/horusdemodlib/uploader.py", line 17, in <module>
    from .habitat import *
  File "/home/pi/horusdemodlib/horusdemodlib/habitat.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Found Rafael Micro R820T tuner
Tuner gain set to automatic.
Tuned to 434578000 Hz.
Oversampling input by: 32x.
Oversampling output by: 1x.
Buffer size: 5.33ms
Sampling at 1536000 S/s.
Output at 48000 Hz.
Signal caught, exiting!

User cancel, exiting..

**Comment by darksidelemm** [comment]
This suggests that you haven't installed the required python libraries correctly. 
```
ModuleNotFoundError: No module named 'requests'
```

Please ensure you've installed the required dependencies as per: https://github.com/projecthorus/horusdemodlib/wiki/1.2--Raspberry-Pi-'Headless'-RX-Guide#25-installing-the-horusdemodlib-python-library

**Comment by heijsteeg** [comment]
Thx that did the trick. 
Somehow had to perform this as admin. Using sudo bash instead of just sudo.

**Comment by darksidelemm** [comment]
If you've set up device access permissions correctly, there shouldn't be any need to run things as sudo. Anyway, I'll close this issue now.
