### ISSUE TITLE
ID 379 change please

### ISSUE THREAD

**Issue by zanco** [projecthorus/horusdemodlib#184]
Hi, can ID 379 temporarily (until we request) be changed to 

SPECTRE 

(without 4fsk ) for the upcoming jota flight ? 

(scheduled for saturday the 21th of October 08:30 UTC, 17 balloons on one frequency )

Thanks!

**Comment by darksidelemm** [comment]
So this *can* be done, but you should be aware that any station that hasn't restarted between when I change it and the flight will still possibly upload with the old callsign. It's probably better to just allocate another v2 ID.

**Comment by darksidelemm** [comment]
OK, that's done. You might want to remind people to restart their stations! 
(Also remind them to update :-) )

**Comment by zanco** [comment]
Did that, on the FB channel, thanks !

Op wo 27 sep 2023 om 00:49 schreef Mark Jessop ***@***.***>:
