### ISSUE TITLE
Payload ID V2 Request

### ISSUE THREAD

**Issue by df9ik** [projecthorus/horusdemodlib#186]
Hi Mark,

can I get a payload ID V2 for DK0WT-4FSK ?

73 Ralf

**Comment by darksidelemm** [comment]
Hi,

I've allocated payload ID 459 to the callsign 'DK0WT' - let me know if you really want the -4FSK suffix, since I don't normally add those anymore (SondeHub-Amateur provides into on the modulation type now).

**Comment by darksidelemm** [comment]
Oh hold on... i see on the map that you are using the callsign DK0WT from your wenet-derived tracker (lacerta? is this on github anywhere?)
I'll adjust this one to DK0WT-V2.
