### ISSUE TITLE
Payload ID Request:  K4KDR-11

### ISSUE THREAD

**Issue by K4KDR** [projecthorus/horusdemodlib#189]
Greetings!

Not ready to fly yet, but have done a lot of ground testing & found the settings that suit my situation.  It would be great to put my code into 'final form' with a real ID number as I accumulate the last few items.

Could I please get an ID for:

K4KDR-11

Question: would I use the **same ID #** for future flights that are configured to use the exact same call sign + SSID?    Or do you designate the ID #'s per each specific flight?  Many thanks from a first-timer.   

-Scott,  K4KDR

**Comment by darksidelemm** [comment]
Hi Scott, 

I've allocated Horus V2 payload ID 464 to "K4KDR". Note that we don't use the SSIDs on Horus Binary callsigns - this isn't APRS!

You just use the same ID for all flights. Data can be extracted from the sondehub db via date/time-range selection.

Cheers,
Mark VK5QI

**Comment by K4KDR** [comment]
Thanks a million!!
