### ISSUE TITLE
Payload id request

### ISSUE THREAD

**Issue by sp6qkm** [projecthorus/horusdemodlib#19]
Hello.

Please set the payload ID

line 53
position 43

SP6QKM-4FSK

Thank you

Marek SP6QKM 
73!

**Comment by sp6qkm** [comment]
Hi, is there a chance to give me another ID 43 for SP6QKM. I am planning to roll out several transmitters this week. No ID will prevent me from sending a transmitter from 4FSK. Thank you very much in advance.
Marek

**Comment by darksidelemm** [comment]
Sorry!  Missed this one. Assigned ID 43 to SP6QKM-4FSK
