### ISSUE TITLE
Payload ID request

### ISSUE THREAD

**Issue by papasven** [projecthorus/horusdemodlib#192]
Hi
Request a payload ID for "S0NDE".

Thank you, carry on.

Sven aka EDDB2 aka ...

**Comment by darksidelemm** [comment]
Hi, I would prefer that payload callsigns be a bit more unique than 'S0NDE'. Can you think of something else?

**Comment by papasven** [comment]
Ah ok then 'FlightKW'.

**Comment by darksidelemm** [comment]
All done, assigned Horus V2 ID 468 to FlightKW
