### ISSUE TITLE
Payload-id list

### ISSUE THREAD

**Issue by F5IKO10** [projecthorus/horusdemodlib#194]
Hello.
Thank you for adding my callsign in the amateur balloon payload-id:

F5IKO-4FSK

Many thanks, best regards and 73 de F5IKO / JN18SJ

**Comment by darksidelemm** [comment]
Payload ID 488 assigned to F5IKO. (note that we don't use the -4FSK suffix anymore, as amateur.sondehub.org will display the modulation type now)
