### ISSUE TITLE
Add AJ4XE custom fields to horusdemodlib

### ISSUE THREAD

**Issue by SteveRan** [projecthorus/horusdemodlib#195]
Add the following to horusdemodlib / custom_field_list.json :

    "AJ4XE": {
    "comment": "custom fields for AJ4XE tracker",
    "struct": "<HHBHH",
    "fields": [
        ["HDOP", "divide_by_100"],
        ["VDOP", "divide_by_100"],
        ["TTF", "none"],
        ["PDOP", "divide_by_100"]
        ["AVE SNR", "divide_by_100"]
    ]
},

   [custom_field_list.json](https://github.com/projecthorus/horusdemodlib/files/13603443/custom_field_list.json)

**Comment by darksidelemm** [comment]
OK, this should be done - please test!
(I added an underscore between AVE and SNR btw)
