### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by Dirk-DJ2DS** [projecthorus/horusdemodlib#196]
Hello
Thank you for your great software project.
I have followed many balloons in the past. In the future I would also like to launch balloons.
Can you send me some Payload id's?
DJ2DS
DS-11

Thank you!
73 Dirk DJ2DS

**Comment by darksidelemm** [comment]
Have assigned the following:
489, DJ2DS
490, DS-11

73
Mark VK5QI
