### ISSUE TITLE
Baudrate or SymbolRate

### ISSUE THREAD

**Issue by sp3rat** [projecthorus/horusdemodlib#20]
Hi, 
How to set baudrate to RTTY, without horus-gui?
sp3rat

**Comment by BoXJakub** [comment]
każdy ładunek ma podany.. przeważnie lecą na 100, lecz zdarzają się na 50.
Pzdr Jakub SQ3XBD

**Comment by darksidelemm** [comment]
The --rate argument to horus_demod allows you to set the baud rate. Be aware that baud rates < 50 baud are not supported.
