### ISSUE TITLE
New custom fields for kd2eat DFM17 testing

### ISSUE THREAD

**Issue by kd2eat** [projecthorus/horusdemodlib#204]
"KD2EAT": {
    "comment": "custom fields for KD2EAT DFM17 testing",
    "struct": "<hhBHBx",
    "fields": [
        ["ascent_rate", "divide_by_100"],
        ["ext_temperature", "divide_by_10"],
        ["ext_humidity", "none"],
        ["ext_pressure", "divide_by_10"]
        ["mcu_calibration", "none"]
    ]
},

**Comment by darksidelemm** [comment]
Done, but for a separate payload ID 501, KD2EAT-DFM
