### ISSUE TITLE
custom_field_add for df7pn

### ISSUE THREAD

**Issue by whallmann** [projecthorus/horusdemodlib#208]
Hi Mark, 
would you please add this custom_field_list to the repository.
I will experiment a bit.
Maybe you are able to translate the field "sonde_type" from a number into text? 
The list is appended below. Tnx. Wolf DF7PN
```
"DF7PN": {
    "comment": "private values see https://github.com/whallmann/RS41HUP_V2",
    "struct": "<HHxxxx",
    "fields": [
        ["flight_number", "none"],
        ["sonde_type", "none"]
    ]
},
```

**Comment by whallmann** [comment]
So this is the edited version of my request. please drop it to the list. Thanks.

**Comment by darksidelemm** [comment]
Done!

**Comment by whallmann** [comment]
Any idea why horusdemodlib says that there is an error in fieldlist (8) after restart?

**Comment by darksidelemm** [comment]
Because the struct field was missing a 'x' to make it the required 9 bytes :-)

Fixed now.

**Comment by fdrbadmuts-GSN** [comment]
Good afternoon,
I hope I'm in the right place. 
I'm also working on programming the probe and would like to have a logbook. Can anyone help me with this?

"GSN-TS": {
        "comment": "GSNgateway.nl",
        "struct": "<BBBBBHH",
        "fields": [
            ["fix_voltage", "battery_5v_byte"],
            ["io_voltage", "battery_5v_byte"],
            ["reset_voltage", "battery_5v_byte"],
            ["pv_voltage", "divide_by_100"],
            ["time_to_fix", "none"],
            ["uv_max", "none"],
            ["uv_avg", "none"],
            ["flight_number", "none"],
            ["sonde_type", "none"]
        ]
        },

**Comment by darksidelemm** [comment]
This custom field description is invalid.

You have 9 fields, but only 7 entries defined in the struct. 

Please have a look at this: https://github.com/projecthorus/horusdemodlib/wiki/5-Customising-a-Horus-Binary-v2-Packet

**Comment by fdrbadmuts-GSN** [comment]
> This custom field description is invalid.
> 
> You have 9 fields, but only 7 entries defined in the struct.
> 
> Please have a look at this: https://github.com/projecthorus/horusdemodlib/wiki/5-Customising-a-Horus-Binary-v2-Packet


Sorry, I'm a beginner, but I see what you mean. It should be correct now, thanks.

**Comment by darksidelemm** [comment]
Still not correct. The custom field area is only 9 bytes long. You are going to either need to (carefully) adjust the data types of your fields, or remove some.

**Comment by fdrbadmuts-GSN** [comment]
> Still not correct. The custom field area is only 9 bytes long. You are going to either need to (carefully) adjust the data types of your fields, or remove some.

Okay, I don't quite get it; I'm trying too hard at once. What I'd like is to see how many flights we've taken. Could you help me with that?

**Comment by darksidelemm** [comment]
Please test that you can generate these packets on your tracker and have them decode correctly. Once you've confirmed that, then I can make this change.
Also, note that these fields are just going to show up as numbers on the sondehub-amateur tracker.
