### ISSUE TITLE
please a neeuw user

### ISSUE THREAD

**Issue by sterrehan** [projecthorus/horusdemodlib#215]
PE1GLG
KITE-1
thanks 
Han van der sterre  PE1GLG

**Comment by darksidelemm** [comment]
Done, allocated:
```
522, PE1GLG
523, KITE-1
```

**Comment by sterrehan** [comment]
PE1GLG-APRS a neeuw user

**Comment by darksidelemm** [comment]
I'd rather not be allocating a Horus-Binary ID with 'APRS' in the callsign! This is definitely not APRS...

**Comment by sterrehan** [comment]
Please
PE1GLG -2

**Comment by darksidelemm** [comment]
Done, ID 600
