### ISSUE TITLE
Custom telemetry

### ISSUE THREAD

**Issue by sp9skp** [projecthorus/horusdemodlib#219]
Hi
Could you add my custom telemetry?
Thanks

"SP9SKP": {
    "comment": "SKP telemetry",
    "struct": "<BBBBBHH",
    "fields": [
        ["fix_voltage", "battery_5v_byte"],
        ["io_voltage", "battery_5v_byte"],
        ["reset_voltage", "battery_5v_byte"],
        ["pv_voltage", "divide_by_100"],
        ["time_to_fix", "none"],
        ["uv_max", "none"],
        ["uv_avg", "none"]
    ]
}

**Comment by darksidelemm** [comment]
OK, this has been added - please test!

Also, really good to see others using the custom telemetry, I hope it works well for you!

**Comment by sp9skp** [comment]
Thanks! 
Looks like it's working fine.
Custom telemetry is really good thing, It's better than APRS telemetry.
