### ISSUE TITLE
Request a Payload ID V2

### ISSUE THREAD

**Issue by pa3eiv** [projecthorus/horusdemodlib#220]
Can you please assign me a new V2 Payload ID for PA3EIV-4FSK-V2.
I was generating errors in the system by using a V1 ID for a V2 Binary Package.

Thank you,

André PA3EIV

**Comment by darksidelemm** [comment]
I've assigned ID 537 to the callsign PA3EIV.
We don't do the -4FSK thing anymore as it's obvious enough on the tracker what mode it is now.

**Comment by Atiracom** [comment]
Hi to all!
Do you generate V2 Payload code for my callsing YU7TDA
Tnx
