### ISSUE TITLE
Horus Binary for 9A4GE-2, ID please

### ISSUE THREAD

**Issue by WildMany** [projecthorus/horusdemodlib#222]
Recently sent two balloons, one with my callsign, another 'borrowed'. But now no way to ask for permission.
So, please ID for 9A4GE-2, 4FSK V2.

Thank you in advance.
73!

**Comment by darksidelemm** [comment]
Done, ID 540

Yes, using someone elses callsign is not recommended!

**Comment by WildMany** [comment]
Thanks! I is permitted by person who have this name "Flybag". So, my balloon is made of DIY mylar foil resembling pillow or bag. Just a coincidence.
