### ISSUE TITLE
Request payload ID

### ISSUE THREAD

**Issue by edegraaff** [projecthorus/horusdemodlib#223]
Hi Mark, 
I am testing with some transmitters for a HAB project somewhere this year. I am using the horys binary tracker build by Roel. 
When i am transmitting i would like to replace the test id 0 and 256 for my own id. 
My call is PD1EG what transmitter will be used in the future is not yet clear. 
Could you add my call PD1EG-4fsk to https://github.com/projecthorus/horusdemodlib/blob/master/payload_id_list.txt  

Regards
Eelco pd1eg

**Comment by darksidelemm** [comment]
Done, assigned payload ID 542 to PD1EG
