### ISSUE TITLE
Payload ID Request "RFA-x"

### ISSUE THREAD

**Issue by MFeiler-RFA** [projecthorus/horusdemodlib#238]
Hi,
I would like to request 3 Payload IDs:

-  `RFA-0`
-  `RFA-1`
-  `RFA-2`

Multiple IDs will be needed, as we might need to launch multiple sondes at the same time. 
Thank you for your work on this awesome project.

**Comment by darksidelemm** [comment]
Done:
```
566, RFA-0
567, RFA-1
568, RFA-2
```
