### ISSUE TITLE
Payload id request

### ISSUE THREAD

**Issue by sp6qkm** [projecthorus/horusdemodlib#24]
Hi, would it be possible to assign an ID to our friend with whom we test 4FSK? Michał SQ6RQT.
We conduct balloon campaigns together with Jakub SQ3XBD and Marek SP6QKM. Thank you in advance

Please set the payload ID 

line 54
position 44

SQ6RQT-4FSK

Regards, Marek SP6QKM

**Comment by darksidelemm** [comment]
Added payload ID for SQ6RQT-4FSK
