### ISSUE TITLE
Update custom telemetry

### ISSUE THREAD

**Issue by sp9skp** [projecthorus/horusdemodlib#240]
Hi!
Could you add custom telemetry for SKPQKM?

"SKPQKM": {
    "comment": "SKPQKM telemetry",
    "struct": "<BBBBBHH",
    "fields": [
        ["fix_voltage", "battery_5v_byte"],
        ["io_voltage", "battery_5v_byte"],
        ["reset_voltage", "battery_5v_byte"],
        ["pv_voltage", "divide_by_100"],
        ["time_to_fix", "none"],
        ["uv_max", "none"],
        ["uv_avg", "none"]
    ]
    }
}

Thanks!
Have a nice day.

**Comment by darksidelemm** [comment]
All done!
