### ISSUE TITLE
Request new Horus V2 IDs

### ISSUE THREAD

**Issue by ClassAxion** [projecthorus/horusdemodlib#241]
Hello. Please add the IDs:
- `SQ2CPA-31` 
- `SQ2CPA-32` 
- `SQ2CPA-33` 

into the ID list. Thanks and 73! Damian SQ2CPA

**Comment by darksidelemm** [comment]
Done:
```
582, SQ2CPA-31
583, SQ2CPA-32
584, SQ2CPA-33
```
