### ISSUE TITLE
Updating payload_id_list

### ISSUE THREAD

**Issue by ziolwk** [projecthorus/horusdemodlib#242]
Hi, 
If you could be so kind as to add the following payload identifiers, I would be very very grateful:

SP8CLR-1
SP8CLR-2
SP8CLR-3
SP8CLR-4
HF8HAY

Thank you!

**Comment by darksidelemm** [comment]
Done:
```
586, SP8CLR-1
587, SP8CLR-2
588, SP8CLR-3
589, SP8CLR-4
590, HF8HAY
```
