### ISSUE TITLE
Payload ID Request

### ISSUE THREAD

**Issue by ke5gdb** [projecthorus/horusdemodlib#243]
Can you add these IDs to the list?

KE5GDB-21
KE5GDB-22
K5RWK
W5NGU
K5PRK

Thanks!

**Comment by darksidelemm** [comment]
I note some of these have APRS-style SSIDs at the end (e.g. 11 for balloons)
Horus Binary is not APRS, and we don't use these SSIDs. We do sometimes use
-2, -3 to represent multiple payloads that might be in the air
simultaneously.

Have a think about if you want these SSIDs on the end and get back to me.
Also don't use the same call sign and SSID as an APRS payload you might
also be flying!

**Comment by ke5gdb** [comment]
Good to know, and thanks for the feedback! This is my first go-round with Project Horus, so it checks out that I make a first-time mistake :) 

Let's go with this list here:

KE5GDB
K5RWK
W5NGU
K5PRK

That includes my callsign and the 3 area clubs that will be sponsoring these flights. If fly two trackers (which is somewhat likely), I'll just use my call and one of the club calls.

Thanks!

**Comment by darksidelemm** [comment]
All done!
```
591, KE5GDB
592, K5RWK
593, W5NGU
594, K5PRK
```
