### ISSUE TITLE
Please add ID

### ISSUE THREAD

**Issue by SQ9CIN** [projecthorus/horusdemodlib#249]
Hi,
  Please add the new ID SQ9CIN-4FSK to the ID list.  Could be the next available number "607".  thank you 
73 SQ9CIN

**Comment by darksidelemm** [comment]
I just added an ID for SQ9CIN, ID 606. Isn't that what you were after?

**Comment by SQ9CIN** [comment]
606 SQ9CIN
607 SQ9CIN-4FSK

won't that be a problem? 🙂

**Comment by darksidelemm** [comment]
Are you planning on having multiple balloons in the air *simultaneously* ? If so I'm happy to allocate SQ9CIN-2. I don't see any need for the -4FSK suffix any more.

**Comment by SQ9CIN** [comment]
if the 4fsk note is not required, leave only ID 606

**Comment by darksidelemm** [comment]
OK. The reason I say there's no need for the -4FSK suffix is that the sondehub-amateur tracker has been showing the modulation type for a very very long time now (since it started!), and so users can figure out what software they need based on that.
