### ISSUE TITLE
Payload ID request

### ISSUE THREAD

**Issue by TSalwach** [projecthorus/horusdemodlib#25]
Hi
Please add those ID's, those are for me and my friends, I'm sending them in single request.
SP6ZWR-13
SQ6QV-13
SQ6NLN-13

73 
Tom SQ6QV

**Comment by darksidelemm** [comment]
Are you sure you want the -13 callsigns? This may get confused with an APRS-sourced call, or if you use APRS trackers as well as this. Are you expecting all of these callsigns to be used? For testing you should be using the 4FSKTEST callsign.

**Comment by TSalwach** [comment]
We will be using RS41 software sending also same position with same callsign by APRS.
If this is a problem for habhub software You can do -4FSK. This is to avoid confusion. 
Yes all those callsigns will be used, sometimes we fly 3 baloons at the same time.

**Comment by darksidelemm** [comment]
Yes, using the same callsign won't end well.

I've allocated the following:
45, SP6ZWR-4FSK
46, SQ6QV-4FSK
47, SQ6NLN-4FSK

73
Mark

**Comment by TSalwach** [comment]
Thanks!
