### ISSUE TITLE
Payload(s) ID Request

### ISSUE THREAD

**Issue by sp9uob** [projecthorus/horusdemodlib#250]
Hi,
Could you please assign payload ID's for my payloads?
SP9UOB
SP9UOB-PICO1
SP9UOB-PICO2
SP9UOB-PICO3
SP9UOB-PICO4
SP9UOB-PICO5

Thanks in advance, Tom.

**Comment by darksidelemm** [comment]
Sorry, I missed this while I was away.

Do you *really* need all these PICOx IDs? I only really want to issue multiple IDs like this if you really are expecting to have this many balloons in the air *simultaneously*.

**Comment by sp9uob** [comment]
Yes, Im plannig on making "pico armada". Picos will be relaying data from each other.

**Comment by darksidelemm** [comment]
OK, all allocated:
```
615, SP9UOB
616, SP9UOB-PICO1
617, SP9UOB-PICO2
618, SP9UOB-PICO3
619, SP9UOB-PICO4
620, SP9UOB-PICO5
```
