### ISSUE TITLE
add entry to custom_field_list.json

### ISSUE THREAD

**Issue by sp9uob** [projecthorus/horusdemodlib#268]
"SP9UOB-PICO1": {
    "comment": "SP9UOB pico series custom fields",
    "struct": "<HHbbHb",
    "fields": [
        ["vcc", "divide_by_100"],
        ["solar", "divide_by_100"],
        ["prefix1", "none"],
        ["prefix2", "none"],
        ["flags", "none"],
        ["ttf", "none"]
    ]
}

**Comment by darksidelemm** [comment]
Done.
