### ISSUE TITLE
Proszę przypisać identyfikator do BSS-4FSK (SQ6NEI)

### ISSUE THREAD

**Issue by Aniolg75** [projecthorus/horusdemodlib#27]

**Comment by Aniolg75** [comment]
Proszę przypisać identyfikator do BSS-4FSK (SQ6NEI)

**Comment by darksidelemm** [comment]
Sorry, which callsign did you want? BSS-4FSK (which already exists) or SQ6NEI-4FSK ?

**Comment by Aniolg75** [comment]
SQ6NEI-4FSK 
Dziękuję

**Comment by darksidelemm** [comment]
OK, assigned ID 49 to SQ6NEI-4FSK
