### ISSUE TITLE
New payload-ID and custom fields

### ISSUE THREAD

**Issue by Nevvman18** [projecthorus/horusdemodlib#271]
Hi,
Could you assign a new ID `NEVVMAN-1` and custom fields for it:

```
"NEVVMAN-1": {
    "comment": "Nevvman's custom fw fields",
    "struct": "<BBBhHH",
    "fields": [
        ["state", "none"],
        ["add1", "none"],
        ["add2", "divide_by_10"],
        ["add3", "divide_by_10"],
        ["add4", "divide_by_10"],
        ["add5", "none"]
    ]
}
```

I'm doing some development work on my firmware for the new sondes and need a working Horus protoype.

Best,
Franek

**Comment by darksidelemm** [comment]
This is done with ID 654.

What new sondes are you referring to? 
If you're doing a Horus v2 implementation, would it be possible for you to try and match the default custom area format that RS41ng produces, at least in part?

**Comment by darksidelemm** [comment]
I should note that I'm trying to make it easier for multiple payloads to use the same non-default custom field definition, but this is going to require some breaking changes in horusdemodlib to implement...

**Comment by Nevvman18** [comment]
Awesome, thanks!
I'm developing custom firmware for new version of RS41 sondes, because the RS41ng doesn't support them.

**Comment by darksidelemm** [comment]
OK, it would be good if you could share your findings for getting things working with RS41ng, I know @mikaelnousiainen would be very interested!

**Comment by Nevvman18** [comment]
Everything is in the development but already there is a repo [here](https://github.com/Nevvman18/rs41-nfw)

**Comment by darksidelemm** [comment]
OK, thanks for that.

Anyway, please considering having the default custom field contents for your Horus v2 packets match the default in horusdemodlib, which are here: https://github.com/projecthorus/horusdemodlib/blob/master/custom_field_list.json#L21
There are 2 bytes free at the end that would be an appropriate place to add status flags or similar. 

Using a different format as the default is going to make life difficult until I re-do the custom field definition system, which is going to be a few months away as I'm very time-poor at the moment.
