### ISSUE TITLE
2 new calls

### ISSUE THREAD

**Issue by PD1NW** [projecthorus/horusdemodlib#282]
Hi would you like to make 2 new calls for the upcoming Jota event?
PA6JAM and PA6JAM/J

Thank you in advance

Greeting,
Rob PD1NW

**Comment by darksidelemm** [comment]
Done:
692, PA6JAM
693, PA6JAM/J

Warning - the callsign with the /J on the end might cause issues in a few places. Let me know if you see anything weird.

**Comment by PD1NW** [comment]
Good morning, just to be sure PA6JAM-J 

Thank you

**Comment by darksidelemm** [comment]
OK, I've made this change.
