### ISSUE TITLE
Installation warning

### ISSUE THREAD

**Issue by videobuff** [projecthorus/horusdemodlib#283]
Raspberry PI 3
Latest raspian - wormhole

While installing the requirements, i noticed this warning coming by.

```
Installing collected packages: crcmod, urllib3, six, numpy, idna, charset-normalizer, certifi, requests, python-dateutil
  DEPRECATION: crcmod is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

```

**Comment by darksidelemm** [comment]
Thanks for the heads up. 
Unfortunately it looks like crcmod isn't being maintained anymore, so we might need to either pull in what we need from it, or go looking for other alternatives. This will apply to wenet, and possibly radiosonde_auto_rx too.

**Comment by darksidelemm** [comment]
https://pypi.org/project/crc/ may be an alternative, though it requires Python 3.8 or newer.

**Comment by videobuff** [comment]
Thanks for the quick replies.  I have a RTL_SDR V4 in use but so far no luck (installed the blog drivers for debian). I have as testdevice a RS41 flashed with Franeks firmware but no reading yet where as it nicely shows on my windows with horus gui. INteresting stuf for a pensioner like me.

**Comment by darksidelemm** [comment]
Unfortunately I can't help much with the RTLSDR v4 (I don't have one). You will probably need to verify that it works with some other software before trying it with horusdemodlib.

I would have hoped that on the latest versions of Raspbian that the v4 updates would have been included.. but maybe not.

**Comment by videobuff** [comment]
All is well know. Installed / updated the RTL_SDR V4 drivers with the following:

```
sudo apt update
sudo apt install libusb-1.0-0-dev git cmake
sudo apt install debhelper

git clone https://github.com/rtlsdrblog/rtl-sdr-blog
cd rtl-sdr-blog
sudo dpkg-buildpackage -b --no-sign
cd ..

sudo dpkg -i librtlsdr0_*
sudo dpkg -i librtlsdr-dev_*
sudo dpkg -i rtl-sdr_*
Now reboot your Pi4 and it should work.
```
Tested it with my own rs41 

```
pi@hampi:~ $ tail -f /home/pi/horusdemodlib/telemetry.log
$$PA0ESH-NFW,1,00:00:00,0.00000,0.00000,0,0,0,25,2.45,0.00,0.0,0,0.0*CBDA
$$PA0ESH-NFW,2,00:00:00,0.00000,0.00000,0,0,0,25,2.43,0.00,0.0,0,0.0*643E
$$PA0ESH-NFW,15,16:25:37,52.25881,6.75799,11,0,8,23,2.35,-0.72,0.0,0,0.0*0FF9
$$PA0ESH-NFW,16,16:26:10,52.25892,6.75795,4,0,8,23,2.33,-0.20,0.0,0,0.0*FAC7
```
It's also working on my autorx station.
