### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by ohitstarik** [projecthorus/horusdemodlib#291]
Hey! Could I get payload ids made?

RETURN-3
RETURN-4

thanks for the project.

**Comment by darksidelemm** [comment]
Before I allocate these, any particular reason why -3 and -4 ?
Payload IDs are meant to be reused, so I don't like using 'mission numbers' as suffixes, if that's what this is.

**Comment by ohitstarik** [comment]
I see. No, not for mission numbers, they are meant to be serial numbers w the payloads they go in. SN 1 & 2 used different tracking devices.

**Comment by darksidelemm** [comment]
OK no problems.

In that case:
```
722, RETURN-3
723, RETURN-4
```
