### ISSUE TITLE
Add systemd service file.

### ISSUE THREAD

**Issue by sp3rat** [projecthorus/horusdemodlib#33]
Hello Mark.
Recently I became interested in your "horusdemodlib" program to receive 4fsk signals on RPI4.
My RPI is without a monitor.
I communicate with her via ssh from my big PC.
How can I run "start_rtlsdr.sh" in the background, without the monitor, with the console closed?
Now, when they close the console, the programm stops.
Jurek

**Comment by sp3rat** [comment]
Hi Mark.
:)
I made own systemd service file. It is working fine.
It was simply.
Thank you.
Jurek

**Comment by edegraaff** [comment]
> Hi Mark. :) I made own systemd service file. It is working fine. It was simply. Thank you. Jurek

Could you share it?  saves others time :-) the simple approach of Mark does work btw, but quick and dirty.

**Comment by darksidelemm** [comment]
There are now (finally) example systemd service files in this repo!
