### ISSUE TITLE
New call

### ISSUE THREAD

**Issue by SP8ESA** [projecthorus/horusdemodlib#34]
Please add SP8ESA
73

**Comment by darksidelemm** [comment]
Sorry, I missed this one. Do you want the callsign to be SP8ESA, or SP8ESA-4FSK as seems to be the convention for 4FSK payloads?

**Comment by SP8ESA** [comment]
Yeah, SP8ESA-4FSK will be OK

**Comment by darksidelemm** [comment]
OK, allocated ID 57 to SP8ESA-4FSK

**Comment by SP8ESA** [comment]
Thanks
