### ISSUE TITLE
New payload ID

### ISSUE THREAD

**Issue by sq5nwi** [projecthorus/horusdemodlib#37]
Hi Mark, could you assign the ID for SP5WWL-4FSK, please?
Thanks in advance. :-)
-- 
73 de Krzysiek (Chris) SQ5NWI

**Comment by darksidelemm** [comment]
Assigned ID 61 to SP5WWL-4FSK. Pretty soon everyone in Poland is going to have their own ID!

**Comment by sq5nwi** [comment]
Yes, there is number of us interested in launching 4FSK trackers. For example I'm involved in two clubs (SP5YAM & SP5WWL) cooperation under common name: https://wstratosfere.pl/ - only in Polish. This is for students and with students activity and your 4FSK software is very atractive for both - ballon missions designers and trackers listeners. :-)
-- 
73 de Krzysiek (Chris) SQ5NWI

**Comment by darksidelemm** [comment]
Hi, just commenting here hoping you will see this.
I see you are using your Horus v1 ID, though are transmitting the Horus V2 mode - while this does seem to work, it is not recommended, as it will result in weird decoder behaviour.

I've allocated ID 439 to the callsign SP5WWL - please use that ID instead!

**Comment by sq5nwi** [comment]
Thank you Mark and sorry for that unintentional mess.We'll correct it in a next flights.Could you do the same for SP5YAM callsign which we also use - sometimes in the same flight with SP5WWL?Thank you in advance.-- 73 de Krzysiek SQ5NWI
-------- Oryginalna wiadomość --------Od: Mark Jessop ***@***.***> Data: 9.07.2023  08:18  (GMT+01:00) Do: projecthorus/horusdemodlib ***@***.***> DW: sq5nwi ***@***.***>, Author ***@***.***> Temat: [SPAM] Re: [projecthorus/horusdemodlib] New payload ID (#37) 
Hi, just commenting here hoping you will see this.
I see you are using your Horus v1 ID, though are transmitting the Horus V2 mode - while this does seem to work, it is not recommended, as it will result in weird decoder behaviour.
I've allocated ID 439 to the callsign SP5WWL - please use that ID instead!

**Comment by darksidelemm** [comment]
Its OK, no mess produced! It was just surprised that it worked! 
I've allocated ID 440 to SP5YAM
