### ISSUE TITLE
My installation fails at pip install -e .

### ISSUE THREAD

**Issue by zanco** [projecthorus/horusdemodlib#40]
Hi, Following the instructions installing the requirements goes all ok:
`Successfully installed certifi-2021.5.30 chardet-4.0.0 crcmod-1.7 idna-2.10 numpy-1.18.5 requests-2.25.1 urllib3-1.26.6
`

pip install -e . however fails with:

> Obtaining file:///home/pi/horusdemodlib
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/horusdemodlib/setup.py", line 14
        raise RuntimeError(f"Cannot find __version__ in {init_file}")
                                                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/pi/horusdemodlib/

Any ideas on this ?

Thanks,
Ben

**Comment by darksidelemm** [comment]
I need to know more information about your platform. What python vversion, etc.

If you are running 'pip' or 'python' on raspbian, this may be using Python 2.7 which is NOT supported.

**Comment by zanco** [comment]
> (venv) pi@pitsatwork:~/horusdemodlib $ which python
/home/pi/horusdemodlib/venv/bin/python
(venv) pi@pitsatwork:~/horusdemodlib $ python
Python 3.5.3 (default, Apr  5 2021, 09:00:41)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

and:

> (venv) pi@pitsatwork:~/horusdemodlib $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch


Any more info needed ?

**Comment by darksidelemm** [comment]
Update to the latest Raspbian (buster) and try again...

**Comment by zanco** [comment]
That solved it. Thanks!
