### ISSUE TITLE
Working directory needs to be set to start on boot 

### ISSUE THREAD

**Issue by Moll1989** [projecthorus/horusdemodlib#42]
In the how-to wiki guide 1.2--Raspberry-Pi-'Headless'-RX-Guide, Section 5 advises how to use rc.local to start on boot, however the start_rtlsdr.sh script fails because it needs to be run from the horusdemodlib folder.

The code block which reads:
`/home/pi/horusdemodlib/start_rtlsdr.sh &`
should read:
`cd /home/pi/horusdemodlib`
`/home/pi/horusdemodlib/start_rtlsdr.sh &`

Otherwise the script will fail every time.

**Comment by darksidelemm** [comment]
Have added cd's to the start of the scripts.
