### ISSUE TITLE
CMakeLists.txt is in the top directory.

### ISSUE THREAD

**Issue by Derek000** [projecthorus/horusdemodlib#43]
Perhaps it was my install method, but after install I ended up with a /horusdemodlib/horusdemodlib/build directory. This then required me to create a do a /horusdemodlib/horusdemodlib/build$ cmake ../../

It looks like the install CMakeLists.txt is in the /horusdemodlib/

**Comment by darksidelemm** [comment]
Errrrr, not sure how you ended up with this? It should just be:
```
mkdir build && cd build
cmake ../
```
As per https://github.com/projecthorus/horusdemodlib/wiki/1.2--Raspberry-Pi-'Headless'-RX-Guide#24-compiling-horusdemodlib
