### ISSUE TITLE
New payload ID

### ISSUE THREAD

**Issue by boonie-oet-gelaen** [projecthorus/horusdemodlib#45]
Hi,

Requesting an ID for

PE1PSI-4FSK

73
Dave

**Comment by darksidelemm** [comment]
Assigned ID #68 to PE1PSI-4FSK
(Nice callsign!)

**Comment by boonie-oet-gelaen** [comment]
Thanks and thanks. The callsign was pure luck. Pitty was that the company did not want to sponsor me for an opportunity to design QSL cards for me.
