### ISSUE TITLE
New payload ID

### ISSUE THREAD

**Issue by sq3dvq** [projecthorus/horusdemodlib#48]
Hello, I like to ask for the Payload ID for:

SQ3GJS-4FSK
SP3PWL-4FSK
SQ3DVQ-4FSK

Thank you, goodbye
Kris, SQ3DVQ

**Comment by darksidelemm** [comment]
Are these all for testing or for actual flights? It's like 50% of hams in Poland have a 4FSK ID now :-)

**Comment by sq3dvq** [comment]
For flights. We are planning the next one on Sunday

**Comment by darksidelemm** [comment]
OK, assigned the following IDs:
72, SQ3GJS-4FSK
73, SP3PWL-4FSK
74, SQ3DVQ-4FSK

Don't forget to update horus-gui and horusdemodlib, as I'll be trying to switch new users over to the Horus Binary v2 mode in coming months.

**Comment by sq3dvq** [comment]
Thank you for the information and adding to the list.

**Comment by SP6TKN** [comment]
Hello, please give me an ID for: 
SP6TKN-4FSK

Thank you very much.

**Comment by darksidelemm** [comment]
Done, ID #82 assigned.

**Comment by SP6TKN** [comment]
Thanks a lot for adding :)

**Comment by SP6TKN** [comment]
hello, please ID V2.
SP6TKN-V2.  

Thank you very much.
