### ISSUE TITLE
New payload ID

### ISSUE THREAD

**Issue by sp6qkm** [projecthorus/horusdemodlib#49]
Hello, I like to ask for the Payload ID for:

SP9SKP-4FSK

Thank you, goodbye
Marek, SP6QKM

**Comment by darksidelemm** [comment]
Assigned 75 to SP9SKP-4FSK

**Comment by darksidelemm** [comment]
Hi Marek,

You might want to put the word out to your listeners that they should update their version of Horus-GUI or horusdemodlib. There have been lots of updates, and I see there are still stations running v0.1.x

In particular, these older stations will not be able to decode any payloads running the v2 mode...

73
Mark

**Comment by sp6qkm** [comment]
W dniu 2022-03-06 12:28, Mark Jessop napisał(a):
> Hi Marek,
> 
> You might want to put the word out to your listeners that they should
> update their version of Horus-GUI or horusdemodlib. There have been
> lots of updates, and I see there are still stations running v0.1.x
> 
> In particular, these older stations will not be able to decode any
> payloads running the v2 mode...
> 
> 73
> Mark


Hello Mark.

I forwarded the information to my friends to use the new V2 version.
Would it be possible to assign an ID to V2.
SP6QKM-4FSK2
SP6ZWR-4FSK2
SQ6NLN-4FSK2
SQ6ODL-4FSK2
SQ6RQT-4FSK2
SP6ZHP-4FSK2

Thank you in advance.
Hi.
Marek

**Comment by darksidelemm** [comment]
Do you wan to use this convention, or the CALLSIGN-V2 convention that seems to be in use? (check the payload id list)

**Comment by sp6qkm** [comment]
W dniu 2022-03-07 22:16, Mark Jessop napisał(a):
> Do you wan to use this convention, or the CALLSIGN-V2 convention that
> seems to be in use? (check the payload id list)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>


I am thinking of a separate ID for the V2 version.
It can be

279, SP6ZWR-V2,
280, SP6QKM-V2,
281, SQ6RQT-V2,
282, SQ6NLN-V2,
283, SP6ZHP-V2,
284, SQ6ODL-V2.


Leave the previous ID for V1 unchanged


Is it okay?

**Comment by darksidelemm** [comment]
Done!

**Comment by sp6qkm** [comment]
Hello, would it be possible to assign the ID 108 SP2SGF-4FSK and 295 
SP2SGF-V2
Thanks in advance.
73! Marek

**Comment by darksidelemm** [comment]
Done
