### ISSUE TITLE
Requesting custom field list.

### ISSUE THREAD

**Issue by hexameron** [projecthorus/horusdemodlib#50]
```
"MAGNU": {
    "struct": "<hHhHb",
    "fields": [
        ["Vertical", "divide_by_100"],
        ["Lateral", "divide_by_100"],
        ["Orthogonal", "divide_by_100"],
        ["Travel", "divide_by_100"],
        ["Heading", "divide_by_100"]
    ]
}
```
Mostly for ground testing, but I have some balloons to use up at some point.

Well done for making v2 a painless switchover; the extra fields should allow for some interesting payloads.

**Comment by darksidelemm** [comment]
I'd probably suggest using a different payload ID for the v2 payloads ('MAGNU-V2'). While I think the decoder *should* handle a v2 packet with a <256 payload ID, its probably best to keep them separate for now.

Do you want me to allocate you a >256 ID with a different callsign?

**Comment by hexameron** [comment]
I think it would be sensible to use "MAGNU-V2". It is working with the V1 ID, but that does limit my ability to use obsolete payloads in the future. Thanks.

**Comment by darksidelemm** [comment]
OK, this is done! It will be good to see a V2 payload on the air :-)

**Comment by darksidelemm** [comment]
Should have said - Payload ID #258 is assigned to callsign MAGNU-V2

**Comment by hexameron** [comment]
I might be able to road-test this afternoon. Thanks.
