### ISSUE TITLE
New payload ID SP6ZHP-4FSK

### ISSUE THREAD

**Issue by sp6qkm** [projecthorus/horusdemodlib#55]
Hello, I like to Request a payload ID for SP6ZHP-4FSK.
SP6ZHP It is a scout communication club.

Thank You, 73!

**Comment by darksidelemm** [comment]
Assigned ID 89

**Comment by darksidelemm** [comment]
@sp6qkm I just noticed a flight from your location with the callsign HORUSBINARY. Please don't do this. It's akin to coming up on an amateur radio band using someone else's callsign. 

Also, it would be worth updating your receiver station, horus-gui v0.1.16 is well and truly out of date now - we are now up to v0.3.8, which has many improvements and features: https://github.com/projecthorus/horus-gui/releases

**Comment by sp6qkm** [comment]
Hello, there is an error in the programming of the rs41 probe. Id 43 was
 added but the program did not realize it. I corrected the error and it 
won't happen again. The probe also broadcast the signs aprs sp6qkm-13 
and LoRaWan SP6QKM13 sie 2022 03:11 Mark Jessop ***@***.***> napisał(a):
@sp6qkm I just noticed a flight from your location with the callsign HORUSBINARY. Please don't do this. It's akin to coming up on an amateur radio band using someone else's callsign.
Also, it would be worth updating your receiver station, horus-gui v0.1.16 is well and truly out of date now - we are now up to v0.3.8, which has many improvements and features: https://github.com/projecthorus/horus-gui/releases

**Comment by darksidelemm** [comment]
Was the lorawan on a separate payload, or is this some new firmware for the RS41 with a lora module attached?

**Comment by sp6qkm** [comment]
It is a new tested software which includes aprs, lora, 4fsk, Ft8. The problem arose at the header and therefore the id 43 was not sent. There was no time for a thorough verification because I had to fit in the NOTAMs time window. When the program is fully functional, I will pass it to you.13 sie 2022 07:35 Mark Jessop ***@***.***> napisał(a):
Was the lorawan on a separate payload, or is this some new firmware for the RS41 with a lora module attached?
