### ISSUE TITLE
Request a payload ID for 9A4AM-V2

### ISSUE THREAD

**Issue by 9A4AM** [projecthorus/horusdemodlib#58]
Hi,
I like to Request a payload ID for 9A4AM-V2, v2 telemetry format.

Thanks!

**Comment by darksidelemm** [comment]
Rare that I get a request for a V2 ID! Assigned ID 259.

Are you using any of the extra bytes for additional data? If so, we'll need to add an entry into the custom fields list as well. See here: https://github.com/projecthorus/horusdemodlib/wiki/5-Customising-a-Horus-Binary-v2-Packet
