### ISSUE TITLE
ID request

### ISSUE THREAD

**Issue by sq1fyb** [projecthorus/horusdemodlib#61]
Hi Mark,
Can You assign an V1 Id for SQ1FYB-4FSK and V2 ID for same call?

Thanks in advance.
Andy sq1fyb

**Comment by darksidelemm** [comment]
Hi, it's not possible to have a V1 and V2 ID with the same callsign. I can do different callsigns for the different IDs?

**Comment by sq1fyb** [comment]
Yes please. May be v1 ID SQ1FYB-4FSK and V2 ID SQ1FYB-V2 or what is better for you.

**Comment by darksidelemm** [comment]
OK, assigned IDs 97 and 262.

**Comment by SQ3MP** [comment]
Hi, can I also get ID ? 
SQ3MP-4FSK and V2 ID for same call
Thank You in advance

**Comment by darksidelemm** [comment]
Which are you planning on actually using?

**Comment by SQ3MP** [comment]
Both, if possible give me ID for both

sob., 19 lut 2022, 23:12 użytkownik Mark Jessop ***@***.***>
napisał:

**Comment by darksidelemm** [comment]
OK, ID 100 assigned to SQ3MP-4FSK, id 263 to SQ3MP-V2

**Comment by SQ3MP** [comment]
Thank You very much

niedz., 20 lut 2022, 09:21 użytkownik Mark Jessop ***@***.***>
napisał:
