### ISSUE TITLE
Request for a Payload ID

### ISSUE THREAD

**Issue by pa3eiv** [projecthorus/horusdemodlib#64]
I would like to request a payload id for PA3EIV-4FSK.

Kind regards,
André

**Comment by darksidelemm** [comment]
Are you using RS41HUP or RS41ng? If using RS41ng, would you consider having a Horus v2 ID allocated instead?
The callsign convention for this at the moment is something like PA3EIV-V2

**Comment by pa3eiv** [comment]
Hi Mark, i am using rs41hup.

Tnx, Andre

Op ma 7 mrt. 2022 22:23 schreef Mark Jessop ***@***.***>:

**Comment by darksidelemm** [comment]
In that case, ID 105 assigned.

**Comment by pa3eiv** [comment]
Thanks, Mark

Op ma 7 mrt. 2022 22:33 schreef Mark Jessop ***@***.***>:
