### ISSUE TITLE
Add V2 Call Signs

### ISSUE THREAD

**Issue by Yerington** [projecthorus/horusdemodlib#66]
Hi Mark,

Would you please add the following call signs to the payload_id_list?

KQ6RS-V2
KA9Q-V2
KN6SPE-V2
KN6SNE-V2
KN6SNF-V2
WB9COY-V2

Thank you,

David
WD6DRI

**Comment by darksidelemm** [comment]
Assigned the following IDs:

285, KQ6RS-V2
286, KA9Q-V2
287, KN6SPE-V2
288, KN6SNE-V2
289, KN6SNF-V2
290, WB9COY-V2

For these to show up on HabHub, you will need to create a payload document for each of them:
* Visit http://habitat.habhub.org/genpayload/
* Under 'Payload Configuration Documents' select 'Start from existing'
* In the search box, enter 'Horus Binary v2 - W6SUN-V2' which should result in just one result appearing. Click on that.
* Update the payload name (e.g. replace the callsign)
* Under parser configuration, click 'edit'.
* In the callsign field, replace the callsign, then scroll to the bottom of the page and click 'save'.
* Click save at the bottom of the page.
* Your payload telemetry should now appear in Habitat!
* If it doesn't appear, you can debug what's happening by looking at the parser logtail here: http://habitat.habhub.org/logtail/
