### ISSUE TITLE
ID Request

### ISSUE THREAD

**Issue by 9A6NDZ** [projecthorus/horusdemodlib#75]
Hi,
I like to Request a two payload ID's V1
1. for my Radio Club 9A1GIJ-4FSK
2. for my friend 9A9Y-4FSK

**Comment by darksidelemm** [comment]
Have you thought about using RS41ng and the new V2 mode? We have many more payload IDs available there...

**Comment by darksidelemm** [comment]
What's stopping you from updating? There's been versions of the decoders capable of decoding the v2 telemetry for a long time now.

**Comment by 9A6NDZ** [comment]
I'm doing programming on WINDOWS 10 and I don't have a device on Linux with which I could compile V2.

**Comment by darksidelemm** [comment]
Sigh. There's always virtual machines. Please consider getting this sorted. 
I have a limited number of V1 IDs, and with what seems like half of all polish amateur reserving their own ID (and then never showing up on the map), I'm worried I'm going to run out.

```
112, 9A1GIJ-4FSK
113, 9A9Y-4FSK
```

**Comment by 9A6NDZ** [comment]
Thank you very much

**Comment by darksidelemm** [comment]
Also worth noting that your payload document is wrong. The field named as 'GPS Error' is actually ground speed, in kph.
