### ISSUE TITLE
V1 payload ID requests

### ISSUE THREAD

**Issue by kd2eat** [projecthorus/horusdemodlib#76]
Hiya,  Two things:

1) Can you please change my v1 Payload ID from "kd2eat" to "kd2eat-4fsk" to conform to what most other folks are doing.  I do like it better on the map, as it makes the source clearer.
2) Can you please issue another v1 Payload ID as "w2cxm-4fsk", the Amateur Radio Club at Cornell?  I'm the callsign trustee and advisor.

Thanks!
Hojo

**Comment by darksidelemm** [comment]
Both of these changed have been made.

W2CXM-4FSK has been assigned v1 payload ID 115
