### ISSUE TITLE
Payload request

### ISSUE THREAD

**Issue by cyberknol** [projecthorus/horusdemodlib#8]
Hello again, 
I like to request also a payload ID for PA3ARK

PA3ARK, Berend in QTH Nieuwolda, The Netherlands

Best 73s, Peter de PA1SDB

**Comment by cyberknol** [comment]
Ping

**Comment by darksidelemm** [comment]
Sorry, missed this one.

32 = PA3ARK-4FSK

**Comment by cyberknol** [comment]
tnx


Op do 5 nov. 2020 om 21:35 schreef Mark Jessop <notifications@github.com>:
