### ISSUE TITLE
Change call sign OH3VHH to OH3HAB

### ISSUE THREAD

**Issue by mikaelnousiainen** [projecthorus/horusdemodlib#84]
We got a new call sign for our flights (and the old one is no longer valid for this use).

Please change:
ID 66: OH3VHH-4FSK  -> OH3HAB-4FSK
ID 257: OH3VHH-4FSK-V2 -> OH3HAB-4FSK-V2

Thanks!

**Comment by darksidelemm** [comment]
Done!
