### ISSUE TITLE
Alternative call signs for OH3HAB

### ISSUE THREAD

**Issue by mikaelnousiainen** [projecthorus/horusdemodlib#87]
Alternative call signs for OH3HAB are useful when we have transmissions on multiple bands.

Could you please add Horus V2 call signs:

* OH3HAB-2-4FSK-V2
* OH3HAB-3-4FSK-V2

Thanks!

**Comment by darksidelemm** [comment]
303, OH3HAB-2-4FSK-V2
304, OH3HAB-3-4FSK-V2
