### ISSUE TITLE
Payload ID request - ON4IR

### ISSUE THREAD

**Issue by ManoDaSilva** [projecthorus/horusdemodlib#93]
Hi! 
I'd like to request a payload ID (Horus V2) for an upcoming launch in Belgium. Callsign would be ON4IR

I'm also planning to use a custom field, here's the entry:
```
"ON4IR": {
    "comment": "ON4IR - UBA/IRM balloon custom fields",
    "struct": "<HHBHxx",
    "fields": [
        ["geiger_cpm", "none"],
        ["ext_temperature", "divide_by_10"],
        ["ext_humidity", "none"],
        ["ext_pressure", "divide_by_10"]
    ]
},
```

Thank you for your help!

**Comment by darksidelemm** [comment]
Hi @ManoDaSilva - I mentioned in the RS41ng issue that it would be better to put the count-per-minute value right at the end of the custom field area - that way the first few fields can be kept all the same. The two bytes at the end are still free.

Are you actually going to be using a geiger counter, or some other radiation sensor (e.g. photodiode based)?

I've assigned v2 ID 310 to ON4IR, but havent updated the custom field bit yet.

**Comment by ManoDaSilva** [comment]
Hi Mark, thanks for the ID! 

You're right, something like this:
`"ON4IR": {
    "comment": "ON4IR - UBA/IRM balloon custom fields",
    "struct": "<HHBHHH",
    "fields": [
        ["ascent_rate", "divide_by_100"],
        ["ext_temperature", "divide_by_10"],
        ["ext_humidity", "none"],
        ["ext_pressure", "divide_by_10"],
        ["pulse_counts", "none"]
    ]
},`
Would be a bit more logical. 



> Are you actually going to be using a geiger counter, or some other radiation sensor (e.g. photodiode based)?
I was planning on using a geiger counter I built (based off DIYGeigerCounter's design-555 timer as a boost converter, an a single transistor for pulse detection. (which makes me think it could be useful for other designs, I'll create a repo for it)

**Comment by darksidelemm** [comment]
OK, i've added that custom field data in!

**Comment by ManoDaSilva** [comment]
Thank you! 
BTW, here's the [repository for the Geiger Counter](https://github.com/ManoDaSilva/YAGC)

**Comment by ManoDaSilva** [comment]
Hi @darksidelemm , I might've done something wrong, HorusGUI reports incorrect struct length. It does decode though, albeit the value gets divided by 10...
`2022-08-15 20:36:13,266 ERROR: Struct field for ON4IR has incorrect length (11).`

**Comment by ManoDaSilva** [comment]
Yup, one extra byte...

```
"ON4IR": {
    "comment": "ON4IR - UBA/IRM balloon custom fields",
    "struct": "<HHBHHH",
    "fields": [
        ["geiger_cpm", "none"],
        ["ext_temperature", "divide_by_10"],
        ["ext_humidity", "none"],
        ["ext_pressure", "divide_by_10"],
        ["pulse_counts","none"]
    ]
},
```

Should instead be:
```
"ON4IR": {
    "comment": "ON4IR - UBA/IRM balloon custom fields",
    "struct": "<HHBHH",
    "fields": [
        ["ascent_rate", "divide_by_100"],
        ["ext_temperature", "divide_by_10"],
        ["ext_humidity", "none"],
        ["ext_pressure", "divide_by_10"],
        ["pulse_counts","none"]
    ]
},
```

Right? 

Sorry about that mishap!

**Comment by darksidelemm** [comment]
No probs, I should have checked it a bit closer. I've made the update.
