### ISSUE TITLE
4FSK ID SP3CET

### ISSUE THREAD

**Issue by sp3cet** [projecthorus/horusdemodlib#98]
....

**Comment by sp3cet** [comment]
..

**Comment by darksidelemm** [comment]
Are you using RS41ng? Could you please use a v2 ID instead of a V1 ID? I would like to retire the Horus Binary V1 mode.

**Comment by sp3cet** [comment]
rs41 v1 please ! thanks !!! my balloons start tomorrow in Brzeziny in
Poland

pt., 9 wrz 2022 o 14:05 Mark Jessop ***@***.***> napisał(a):

**Comment by sp3cet** [comment]
in Burzenin * small city in poland we have technical event with
balloons and many more....
yes i use RS41 from lindenberg :)


pt., 9 wrz 2022 o 14:36 SP3CET Władek ***@***.***> napisał(a):

**Comment by darksidelemm** [comment]
No, I meant are you using the RS41ng codebase? If so, then you can use the Horus Binary v2 mode.

**Comment by sp3cet** [comment]
no, i must have v1, i send my id from 4FSK to SP6QKM to build my software
to RS41. they use only V1 .

pt., 9 wrz 2022 o 14:46 Mark Jessop ***@***.***> napisał(a):

**Comment by sp3cet** [comment]
could you add my Call to 4FSK base, and send me back my number of 4FSK ID ?


pt., 9 wrz 2022 o 14:58 SP3CET Władek ***@***.***> napisał(a):

**Comment by darksidelemm** [comment]
I have assigned a Horus V1 ID of 124, and a V2 ID of 317.

Please impress upon @sp6qkm that Horus Binary v1 is *deprecated* and will no longer be supported. 
I will NO LONGER BE ASSIGNING V1 PAYLOAD IDs. Please update your software such that you can use the Horus Binary v2 format.

**Comment by sp3cet** [comment]
Thanks a lot!  i send youre information to SP6QKM.
thanks
73

pt., 9 wrz 2022 o 15:06 Mark Jessop ***@***.***> napisał(a):
