### ISSUE TITLE
PAYLOAD ID REQUESTS

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/horusdemodlib#99]
Please Submit Payload ID Requests under this Issue.

**NOTE: I will no longer be assigning Horus Binary v1 Payload IDs. I am happy to reassign old ones, however no new IDs will be allocated. Please switch to firmware that supports Horus Binary v2, e.g. [RS41ng](https://github.com/mikaelnousiainen/RS41ng)**

**Comment by ManoDaSilva** [comment]
Hello Mark, can you please assign 4 additional V2 IDs? Some other "crews" need tracking too, and we're adding more sondes to the mix :)
ON4IR-1
ON4IR-2
ON4IR-3
ON4IR-4


Thank you in advance!

**Comment by darksidelemm** [comment]
Allocated the following:
```
318, ON4IR-1
319, ON4IR-2
320, ON4IR-3
321, ON4IR-4
```

**Comment by ManoDaSilva** [comment]
Thank you!
